<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-BR2IMTQ" failures="0" tests="2" name="DemoApp_tests.DragDropDemo" time="20.257" errors="1" timestamp="2024-04-22T13:56:06 SELÄŒ" skipped="1">
  <testcase classname="DemoApp_tests.DragDropDemo" name="ConfigureAppium" time="20.257">
    <error message="Appium HTTP server is not listening at http://127.0.0.1:4723/ after 20000 ms timeout. Consider increasing the server startup timeout value and check the server log for possible error messages occurrences.
Node.js executable path: C:\Program Files\nodejs\node.exe
Arguments: [C:\Users\Veronika\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1]
Server log: [35m[Appium][39m Welcome to Appium v2.5.2
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m&#039;127.0.0.1&#039;[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Veronika\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Attempting to load driver xcuitest...
[35m[Appium][39m Attempting to load driver gecko...
[35m[Appium][39m Requiring driver at C:\Users\Veronika\.appium\node_modules\appium-uiautomator2-driver\build\index.js
[35m[Appium][39m Requiring driver at C:\Users\Veronika\.appium\node_modules\appium-xcuitest-driver\build\index.js
[35m[Appium][39m Requiring driver at C:\Users\Veronika\.appium\node_modules\appium-geckodriver\build\index.js
[35m[Appium][39m AndroidUiautomator2Driver has been successfully loaded in 1.434s
[35m[Appium][39m XCUITestDriver has been successfully loaded in 1.434s
[35m[Appium][39m GeckoDriver has been successfully loaded in 1.434s
[38;5;0m[HTTP][0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
[35m[Appium][39m Could not configure Appium server. It&#039;s possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723
[35m[Appium][39m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723
[35m[Appium][39m     at Server.setupListenHandle [as _listen2] (node:net:1897:16)
[35m[Appium][39m     at listenInCluster (node:net:1945:12)
[35m[Appium][39m     at doListen (node:net:2109:7)
[35m[Appium][39m     at processTicksAndRejections (node:internal/process/task_queues:83:21)
" type="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
      <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: Appium HTTP server is not listening at http://127.0.0.1:4723/ after 20000 ms timeout. Consider increasing the server startup timeout value and check the server log for possible error messages occurrences.
Node.js executable path: C:\Program Files\nodejs\node.exe
Arguments: [C:\Users\Veronika\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 127.0.0.1]
Server log: [35m[Appium][39m Welcome to Appium v2.5.2
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m The autodetected Appium home path: C:\Users\Veronika\.appium
[35m[Appium][39m Attempting to load driver uiautomator2...
[35m[Appium][39m Attempting to load driver xcuitest...
[35m[Appium][39m Attempting to load driver gecko...
[35m[Appium][39m Requiring driver at C:\Users\Veronika\.appium\node_modules\appium-uiautomator2-driver\build\index.js
[35m[Appium][39m Requiring driver at C:\Users\Veronika\.appium\node_modules\appium-xcuitest-driver\build\index.js
[35m[Appium][39m Requiring driver at C:\Users\Veronika\.appium\node_modules\appium-geckodriver\build\index.js
[35m[Appium][39m AndroidUiautomator2Driver has been successfully loaded in 1.434s
[35m[Appium][39m XCUITestDriver has been successfully loaded in 1.434s
[35m[Appium][39m GeckoDriver has been successfully loaded in 1.434s
[38;5;0m[HTTP][0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
[35m[Appium][39m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723
[35m[Appium][39m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723
[35m[Appium][39m     at Server.setupListenHandle [as _listen2] (node:net:1897:16)
[35m[Appium][39m     at listenInCluster (node:net:1945:12)
[35m[Appium][39m     at doListen (node:net:2109:7)
[35m[Appium][39m     at processTicksAndRejections (node:internal/process/task_queues:83:21)

at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:192)
at Appium_tests.BaseTest2.ConfigureAppium(BaseTest2.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: io.appium.java_client.service.local.AppiumServerAvailabilityChecker$ConnectionTimeout: ConnectionTimeout
at io.appium.java_client.service.local.AppiumServerAvailabilityChecker.waitUntilAvailable(AppiumServerAvailabilityChecker.java:72)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:144)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:185)
... 27 more
Caused by: java.net.ConnectException: Connection refused: no further information
at java.base/sun.nio.ch.Net.pollConnect(Native Method)
at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547)
at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
at java.base/java.net.Socket.connect(Socket.java:633)
at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:281)
at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
at io.appium.java_client.service.local.AppiumServerAvailabilityChecker.connectToUrl(AppiumServerAvailabilityChecker.java:79)
at io.appium.java_client.service.local.AppiumServerAvailabilityChecker.waitUntilAvailable(AppiumServerAvailabilityChecker.java:61)
... 29 more
]]>
    </error>
  </testcase> <!-- ConfigureAppium -->
  <system-out/>
  <testcase classname="DemoApp_tests.DragDropDemo" name="DragDropTest" time="0.000">
    <skipped/>
  </testcase> <!-- DragDropTest -->
  <system-out/>
</testsuite> <!-- DemoApp_tests.DragDropDemo -->
